### ISSUE TITLE
Building static HTML failed for path "/"

### ISSUE THREAD

**Issue by RebootGG** [mihaylovin/gatsby-keycloak#1]
Hi, 

The build fails (gatsby build) : 

So far I've not found any workaround. 

```
failed Building static HTML for pages - 0.922s

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


   7 |     }
   8 |     if (!ctx.authClient) {
>  9 |         throw new Error('authClient has not been assigned to ReactKeycloakProvider');
     | ^
  10 |     }
  11 |     var authClient = ctx.authClient, initialized = ctx.initialized;
  12 |     return {


  WebpackError: authClient has not been assigned to ReactKeycloakProvider

  - useKeycloak.js:9
    node_modules/@react-keycloak/web/lib/useKeycloak.js:9:1

  - index.js:5
    src/pages/index.js:5:46
```

**Comment by mihaylovin** [comment]
Hi there,

building the static HTML files requires also to configure `gatsby-ssr.js`. Usually this would be the same as `gatsby-browser.js`, but `keycloak-js` requires the `windows` object, which is not present while building. I managed to build the project by creating `gatsby-ssr.js` with an empty `authClient` in the `ReactKeycloakProvider`.

**gatsby-ssr.js:**
```
import React from 'react'
import { ReactKeycloakProvider } from '@react-keycloak/web'

const Loading = () => <div>Loading...</div>

export const wrapRootElement = ({ element }) => {
        
    return (<ReactKeycloakProvider 
    authClient={{}}
    initOptions={{
        onLoad: "login-required",
    }}
    LoadingComponent={<Loading />}
    >
        {element}
    </ReactKeycloakProvider>)
}
```

I will check for better solutions and hopefully push a fix in the coming days.

**Comment by mihaylovin** [comment]
The fix is pushed, an empty keycloak instance in `gatsby-ssr.js` seems to be the easiest workaround for now.

**Comment by RebootGG** [comment]
Thanks for the update. 

Downgrading `@react-keycloak/web` to version 2.1.3 also fixes the problem, without changes in the original code.
